name: lint

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: /bin/bash scripts/lint.sh
